config/routes.rb
Rails.application.routes.draw do

  mount EpicEditor::Engine => "/"
  root 'questions#index'

  resources :questions, param: :id_token do
    post '/answers', :to => 'responses#create', :as => :responses
  end

  get '/tags', :to => 'tags#index', :as => :tags
  get '/tags/:name', :to => 'tags#show', as: :acts_as_taggable_on_tag

  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    get '/users/edit/password', :to => 'users/registrations#edit_password', as: :edit_password
  end
  get '/users/:id_token', :to => 'users#show', :as => :user
  get '/users', :to => 'users#index', :as => :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="lt">
<head>
  <title>Usuo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- <script src="/epiceditor/js/epiceditor.min.js"></script> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>

    <div class="content">

      <%= link_to "UsuO", root_path, class: "root_path" %>

      <% if user_signed_in? %>
        <%= link_to('Hi, ' + current_user.name, user_path(current_user)) %>
        <%= link_to('Sign Out', destroy_session_path(current_user), :method => :delete) %>
      <% else %>
        <%= link_to('Sign In', new_user_session_path) %>
        <%= link_to('Sign Up', new_user_registration_path) %>
      <% end %>
    
    </div>

  </header>

  <div id="main">
    <div class="content">

      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>

      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>

      <br>
    </div>
  </div>

  <footer>
    <div class="content">
      <p>LGMOA 2016</p>
    </div>
  </footer>

  <% if Rails.env.development? %>
    <div id="debug" class="content">
      <%= debug(params)%>
    </div>
    <%= console %>
  <% end %>
</body>
</html>